// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package transition

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*eip1559ConstantsMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (e Eip1559Constants) MarshalJSON() ([]byte, error) {
	type Eip1559Constants struct {
		BaseFeeChangeDenominator      *hexutil.Big `json:"base_fee_change_denominator" gencodec:"required"`
		BaseFeeMaxIncreaseDenominator *hexutil.Big `json:"base_fee_max_increase_denominator" gencodec:"required"`
		BaseFeeMaxDecreaseDenominator *hexutil.Big `json:"base_fee_max_decrease_denominator" gencodec:"required"`
		ElasticityMultiplier          *hexutil.Big `json:"elasticity_multiplier" gencodec:"required"`
	}
	var enc Eip1559Constants
	enc.BaseFeeChangeDenominator = (*hexutil.Big)(e.BaseFeeChangeDenominator)
	enc.BaseFeeMaxIncreaseDenominator = (*hexutil.Big)(e.BaseFeeMaxIncreaseDenominator)
	enc.BaseFeeMaxDecreaseDenominator = (*hexutil.Big)(e.BaseFeeMaxDecreaseDenominator)
	enc.ElasticityMultiplier = (*hexutil.Big)(e.ElasticityMultiplier)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (e *Eip1559Constants) UnmarshalJSON(input []byte) error {
	type Eip1559Constants struct {
		BaseFeeChangeDenominator      *hexutil.Big `json:"base_fee_change_denominator" gencodec:"required"`
		BaseFeeMaxIncreaseDenominator *hexutil.Big `json:"base_fee_max_increase_denominator" gencodec:"required"`
		BaseFeeMaxDecreaseDenominator *hexutil.Big `json:"base_fee_max_decrease_denominator" gencodec:"required"`
		ElasticityMultiplier          *hexutil.Big `json:"elasticity_multiplier" gencodec:"required"`
	}
	var dec Eip1559Constants
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.BaseFeeChangeDenominator == nil {
		return errors.New("missing required field 'base_fee_change_denominator' for Eip1559Constants")
	}
	e.BaseFeeChangeDenominator = (*big.Int)(dec.BaseFeeChangeDenominator)
	if dec.BaseFeeMaxIncreaseDenominator == nil {
		return errors.New("missing required field 'base_fee_max_increase_denominator' for Eip1559Constants")
	}
	e.BaseFeeMaxIncreaseDenominator = (*big.Int)(dec.BaseFeeMaxIncreaseDenominator)
	if dec.BaseFeeMaxDecreaseDenominator == nil {
		return errors.New("missing required field 'base_fee_max_decrease_denominator' for Eip1559Constants")
	}
	e.BaseFeeMaxDecreaseDenominator = (*big.Int)(dec.BaseFeeMaxDecreaseDenominator)
	if dec.ElasticityMultiplier == nil {
		return errors.New("missing required field 'elasticity_multiplier' for Eip1559Constants")
	}
	e.ElasticityMultiplier = (*big.Int)(dec.ElasticityMultiplier)
	return nil
}
