// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"

	"github.com/ethereum/go-ethereum/common"
)

// MarshalJSON marshals as JSON.
func (t TransactionSigned) MarshalJSON() ([]byte, error) {
	type TransactionSigned struct {
		Hash        common.Hash  `json:"hash"        gencodec:"required"`
		Signature   *Signature   `json:"signature"   gencodec:"required"`
		Transaction *Transaction `json:"transaction" gencodec:"required"`
	}
	var enc TransactionSigned
	enc.Hash = t.Hash
	enc.Signature = t.Signature
	enc.Transaction = t.Transaction
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (t *TransactionSigned) UnmarshalJSON(input []byte) error {
	type TransactionSigned struct {
		Hash        *common.Hash `json:"hash"        gencodec:"required"`
		Signature   *Signature   `json:"signature"   gencodec:"required"`
		Transaction *Transaction `json:"transaction" gencodec:"required"`
	}
	var dec TransactionSigned
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Hash == nil {
		return errors.New("missing required field 'hash' for TransactionSigned")
	}
	t.Hash = *dec.Hash
	if dec.Signature == nil {
		return errors.New("missing required field 'signature' for TransactionSigned")
	}
	t.Signature = dec.Signature
	if dec.Transaction == nil {
		return errors.New("missing required field 'transaction' for TransactionSigned")
	}
	t.Transaction = dec.Transaction
	return nil
}
