// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*consolidationRequestMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (c ConsolidationRequest) MarshalJSON() ([]byte, error) {
	type ConsolidationRequest struct {
		SourceAddress common.Address `json:"source_address" gencodec:"required"`
		SourcePubkey  hexutil.Bytes  `json:"source_pubkey"  gencodec:"required"`
		TargetPubkey  hexutil.Bytes  `json:"target_pubkey"  gencodec:"required"`
	}
	var enc ConsolidationRequest
	enc.SourceAddress = c.SourceAddress
	enc.SourcePubkey = c.SourcePubkey[:]
	enc.TargetPubkey = c.TargetPubkey[:]
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (c *ConsolidationRequest) UnmarshalJSON(input []byte) error {
	type ConsolidationRequest struct {
		SourceAddress *common.Address `json:"source_address" gencodec:"required"`
		SourcePubkey  *hexutil.Bytes  `json:"source_pubkey"  gencodec:"required"`
		TargetPubkey  *hexutil.Bytes  `json:"target_pubkey"  gencodec:"required"`
	}
	var dec ConsolidationRequest
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.SourceAddress == nil {
		return errors.New("missing required field 'source_address' for ConsolidationRequest")
	}
	c.SourceAddress = *dec.SourceAddress
	if dec.SourcePubkey == nil {
		return errors.New("missing required field 'source_pubkey' for ConsolidationRequest")
	}
	if len(*dec.SourcePubkey) != len(c.SourcePubkey) {
		return errors.New("field 'source_pubkey' has wrong length, need 48 items")
	}
	copy(c.SourcePubkey[:], *dec.SourcePubkey)
	if dec.TargetPubkey == nil {
		return errors.New("missing required field 'target_pubkey' for ConsolidationRequest")
	}
	if len(*dec.TargetPubkey) != len(c.TargetPubkey) {
		return errors.New("field 'target_pubkey' has wrong length, need 48 items")
	}
	copy(c.TargetPubkey[:], *dec.TargetPubkey)
	return nil
}
