// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/common/math"
)

var _ = (*txEip1559Marshaling)(nil)

// MarshalJSON marshals as JSON.
func (t TxEip1559) MarshalJSON() ([]byte, error) {
	type TxEip1559 struct {
		ChainId              *math.HexOrDecimal256 `json:"chain_id" gencodec:"required"`
		Nonce                math.HexOrDecimal64   `json:"nonce" gencodec:"required"`
		GasLimit             math.HexOrDecimal64   `json:"gas_limit" gencodec:"required"`
		MaxFeePerGas         *math.HexOrDecimal256 `json:"max_fee_per_gas" gencodec:"required"`
		MaxPriorityFeePerGas *math.HexOrDecimal256 `json:"max_priority_fee_per_gas" gencodec:"required"`
		To                   *common.Address       `json:"to"`
		Value                *math.HexOrDecimal256 `json:"value" gencodec:"required"`
		AccessList           AccessList            `json:"access"`
		Input                hexutil.Bytes         `json:"input" gencodec:"required"`
	}
	var enc TxEip1559
	enc.ChainId = (*math.HexOrDecimal256)(t.ChainId)
	enc.Nonce = math.HexOrDecimal64(t.Nonce)
	enc.GasLimit = math.HexOrDecimal64(t.GasLimit)
	enc.MaxFeePerGas = (*math.HexOrDecimal256)(t.MaxFeePerGas)
	enc.MaxPriorityFeePerGas = (*math.HexOrDecimal256)(t.MaxPriorityFeePerGas)
	enc.To = t.To
	enc.Value = (*math.HexOrDecimal256)(t.Value)
	enc.AccessList = t.AccessList
	enc.Input = t.Input
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (t *TxEip1559) UnmarshalJSON(input []byte) error {
	type TxEip1559 struct {
		ChainId              *math.HexOrDecimal256 `json:"chain_id" gencodec:"required"`
		Nonce                *math.HexOrDecimal64  `json:"nonce" gencodec:"required"`
		GasLimit             *math.HexOrDecimal64  `json:"gas_limit" gencodec:"required"`
		MaxFeePerGas         *math.HexOrDecimal256 `json:"max_fee_per_gas" gencodec:"required"`
		MaxPriorityFeePerGas *math.HexOrDecimal256 `json:"max_priority_fee_per_gas" gencodec:"required"`
		To                   *common.Address       `json:"to"`
		Value                *math.HexOrDecimal256 `json:"value" gencodec:"required"`
		AccessList           *AccessList           `json:"access"`
		Input                *hexutil.Bytes        `json:"input" gencodec:"required"`
	}
	var dec TxEip1559
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.ChainId == nil {
		return errors.New("missing required field 'chain_id' for TxEip1559")
	}
	t.ChainId = (*big.Int)(dec.ChainId)
	if dec.Nonce == nil {
		return errors.New("missing required field 'nonce' for TxEip1559")
	}
	t.Nonce = uint64(*dec.Nonce)
	if dec.GasLimit == nil {
		return errors.New("missing required field 'gas_limit' for TxEip1559")
	}
	t.GasLimit = uint64(*dec.GasLimit)
	if dec.MaxFeePerGas == nil {
		return errors.New("missing required field 'max_fee_per_gas' for TxEip1559")
	}
	t.MaxFeePerGas = (*big.Int)(dec.MaxFeePerGas)
	if dec.MaxPriorityFeePerGas == nil {
		return errors.New("missing required field 'max_priority_fee_per_gas' for TxEip1559")
	}
	t.MaxPriorityFeePerGas = (*big.Int)(dec.MaxPriorityFeePerGas)
	if dec.To != nil {
		t.To = dec.To
	}
	if dec.Value == nil {
		return errors.New("missing required field 'value' for TxEip1559")
	}
	t.Value = (*big.Int)(dec.Value)
	if dec.AccessList != nil {
		t.AccessList = *dec.AccessList
	}
	if dec.Input == nil {
		return errors.New("missing required field 'input' for TxEip1559")
	}
	t.Input = *dec.Input
	return nil
}
